packages:
  - "packages/*"

# 中央版本控制：Catalog 模式
# 修订版本时只需改这里，所有子包自动生效且不产生 git 变更
catalog:
  # 框架核心 (2026.02 最新稳定版)
  vue: ^3.5.27
  vue-router: ^5.0.2
  vant: ^4.9.22

  # 构建工具 (2026.02 最新稳定版)
  vite: ^7.3.1
  typescript: ^5.9.3
  vue-tsc: ^3.2.4
  turbo: ^2.3.3

  # Vite 插件
  "@vitejs/plugin-vue": ^6.0.3
  "@vant/auto-import-resolver": ^1.3.0
  unplugin-vue-components: ^31.0.0
  vite-plugin-dts: ^4.4.0
  rimraf: ^5.0.0
  "@changesets/cli": ^2.29.8
  "@types/node": ^25.1.0

  # 社区提效包
  "@vueuse/core": ^14.1.0
  "@vant/use": ^1.6.0
  "axios": ^1.13.4
  "lodash-es": ^4.17.23
  "@types/lodash-es": ^4.17.12
  "unplugin-auto-import": ^21.0.0
  "postcss-mobile-forever": ^5.0.0

  # 约定式路由与布局
  "unplugin-vue-router": ^0.19.0
  "vite-plugin-vue-layouts": ^0.11.0

  # UnoCSS 与图标系统
  "unocss": ^66.6.0
  "unplugin-icons": ^23.0.0
  "@iconify/json": ^2.2.0
  "@iconify-json/carbon": ^1.2.18

  # 状态管理
  "pinia": ^3.0.4
  "pinia-plugin-persistedstate": ^4.7.1

  # 开发体验增强
  "vite-plugin-vconsole": ^2.1.1
  "vite-plugin-vue-devtools": ^8.0.5
  "@vitejs/plugin-legacy": ^7.2.1

  # 移动端适配
  "@vant/touch-emulator": ^1.5.0
  "vconsole": ^3.15.1

  # 工程化配置
  "autoprefixer": ^10.4.23
  "less": ^4.5.1
  "cross-env": ^10.1.0
  "eslint": ^9.39.2
  "@antfu/eslint-config": ^7.2.0
  "@unocss/eslint-config": ^66.6.0
