shellEmulator: true

trustPolicy: no-downgrade

packages:
  - 'packages/*'

catalog:
  '@types/lodash-es': ^4.17.12
  '@vueuse/core': ^14.1.0
  axios: ^1.13.4
  dayjs: ^1.11.10
  lodash-es: ^4.17.23
  pinia: ^3.0.4
  pinia-plugin-persistedstate: ^4.7.1
  unocss: ^66.6.0
  vue: ^3.5.27
  vue-router: ^5.0.2

catalogs:
  build:
    '@antfu/eslint-config': ^7.2.0
    '@changesets/cli': ^2.29.8
    '@commitlint/cli': ^20.3.1
    '@commitlint/config-conventional': ^20.3.1
    '@commitlint/types': ^20.3.1
    '@iconify-json/carbon': ^1.2.18
    '@types/node': ^25.1.0
    '@unocss/eslint-config': ^66.6.0
    '@vant/auto-import-resolver': ^1.3.0
    '@vitejs/plugin-legacy': ^7.2.1
    '@vitejs/plugin-vue': ^6.0.3
    autoprefixer: ^10.4.23
    cross-env: ^10.1.0
    eslint: ^9.39.2
    eslint-plugin-format: ^0.1.0
    husky: ^9.1.7
    less: ^4.5.1
    lint-staged: ^16.2.7
    turbo: ^2.3.3
    typescript: ^5.9.3
    unplugin-auto-import: ^21.0.0
    unplugin-vue-components: ^31.0.0
    vite: ^7.3.1
    vite-plugin-dts: ^4.4.0
    vite-plugin-vconsole: ^2.1.1
    vite-plugin-vue-devtools: ^8.0.5
    vue-tsc: ^3.2.4

  mobile:
    '@vant/touch-emulator': ^1.5.0
    '@vant/use': ^1.6.0
    postcss-mobile-forever: ^5.0.0
    vant: ^4.9.22
    vconsole: ^3.15.1
